name: update_runner-docker-only

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@main
      - uses: actions/checkout@main
      - uses: actions/checkout@main
        with:
          repository: ${{ secrets.DATA }}
          token: ${{ secrets.GH_TOKEN }}
          path: 'data'
      - name: cp
        run: cp ./data/*.rules ./mark_builder/
      - name: build runner
        run: cd mark_builder && docker build --no-cache --progress=plain -t runner .
      - name: tag
        run: docker tag runner ${{ secrets.ECR_TAG_RUNNER }}
      - name: push
        run: docker push ${{ secrets.ECR_TAG_RUNNER }} >/dev/null
