name: clean-history-binary
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'LICENSE'
  workflow_dispatch:
permissions:
      contents: write
      pull-requests: write
      repository-projects: write

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - uses: kkkgo/Clean-Git-File-History-Action@main
      with:
        size_threshold: 10M
        filenames: '*.xz,*.dat,*.md5sum,*.sha256sum,*.txt'