name: mark-update-4

on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * 4'
permissions:
  contents: write

jobs:
  update_mark:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@main
        with:
          registry-type: public
      - name: Checkout code
        uses: actions/checkout@main
      - name: pull
        run: docker pull ${{ secrets.ECR_TAG_DATA }} >/dev/null
      - name: create
        run: docker create --name data ${{ secrets.ECR_TAG_DATA }}
      - name: cp global_mark.dat.sha256sum
        run: docker cp data:/pub/global_mark.dat.sha256sum global_mark.dat.sha256sum
      - name: cp global_mark.dat
        run: docker cp data:/pub/global_mark.dat global_mark.dat
      - uses: EndBug/add-and-commit@main
        with:
         author_name: Github Actions
         author_email: actions@github.com
         committer_email: actions@github.com
         


  build_runner:
    # needs: build_mark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/checkout@main
        with:
          repository: ${{ secrets.DATA }}
          token: ${{ secrets.GH_TOKEN }}
          path: 'data'
      - name: cp
        run: cp ./data/*.rules ./mark_builder/
      - name: build runner
        run: cd mark_builder && docker build --no-cache --progress=plain -t runner .
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@main
        with:
          registry-type: public
      - name: tag
        run: docker tag runner ${{ secrets.ECR_TAG_RUNNER }}
      - name: push
        run: docker push ${{ secrets.ECR_TAG_RUNNER }} >/dev/null
